apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
data:
  access-key: TFRBSTV0THB2bVdGWlpvM3N5OW9zMNNNBi # 去阿里云申请
  secret-key: UXp0Rm9oeTlEbHpZR1Y3RGJYMFZUaG9jMMMDW5D
