apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web
spec:
  ingressClassName: nginx
  rules:
  - host: "web.cloudnative.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "go-web-service"
            port:
              number: 80
